---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Ensure that code don't have trailing whitespace
      - id: check-ast
        name: Check python abstract syntax trees
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-json
        name: Check JSON files format
      - id: check-shebang-scripts-are-executable
        name: Check that scripts with shebangs are executable
      - id: check-merge-conflict
        name: Check for merge conflicts in code
      - id: end-of-file-fixer
        name: Files should end with empty line
        exclude: ".json"
      - id: double-quote-string-fixer
        name: Strings should be single quoted
      - id: name-tests-test
        name: Tests should begin with test_
        args: ["--django"]
        exclude: "^(?!helpers/)"

      - id: check-added-large-files
        exclude: ^app/assets/echarts\.min\.js$
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        name: lint with ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff
        name: sort imports with ruff
        args: [--select, I, --fix]
      - id: ruff-format
        name: format with ruff
        types_or: [python, pyi]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.10
    hooks:
      - id: uv-lock
      - id: uv-export
        name: uv export --no-dev --output-file=requirements.txt
        args: ["--no-dev", "--output-file=requirements.txt"]
      - id: uv-export
        name: uv export --only-dev --output-file=requirements-dev.txt
        args: ["--only-dev", "--output-file=requirements-dev.txt"]
      - id: uv-export
        name: uv export --output-file=requirements-all.txt
        args: ["--output-file=requirements-all.txt"]
